# Generated by Django 5.0.3 on 2024-03-21 21:45
# Este archivo de migración fue generado por Django 5.0.3 el 21 de marzo de 2024 a las 21:45.

from django.db import migrations, models
# Importa los módulos necesarios de Django para trabajar con migraciones y modelos de base de datos.

class Migration(migrations.Migration):
    # Define una nueva migración que hereda de migrations.Migration.

    initial = True
    # Indica que esta migración es la migración inicial, que establecerá el estado inicial de la base de datos.

    dependencies = []
    # Lista de dependencias. En este caso, no hay ninguna, lo que significa que esta migración no depende de ninguna otra.

    operations = [
        migrations.CreateModel(
            name='Genre',
            # Crea un nuevo modelo llamado 'Genre'.

            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Campo 'id' de tipo BigAutoField, que es un campo autoincremental grande.
                # Se crea automáticamente, es clave primaria y no se serializa (no se convierte en JSON).
                # verbose_name es una etiqueta legible para humanos para este campo, en este caso 'ID'.

                ('name', models.CharField(max_length=100)),
                # Campo 'name' de tipo CharField, que es un campo de texto con longitud máxima de 100 caracteres.
            ],
        ),
    ]
    # Lista de operaciones de migración que se deben realizar.
