# Generated by Django 5.0.3 on 2024-04-12 21:41
# Este archivo de migración fue generado por Django 5.0.3 el 12 de abril de 2024 a las 21:41.

from django.db import migrations, models

class Migration(migrations.Migration):
    # Define una nueva migración.

    dependencies = [
        ('movies', '0003_alter_movie_budget_alter_movie_poster_path_and_more'),
    ]
    # Establece las dependencias de esta migración.

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
        # Altera el campo 'budget' del modelo 'Movie' para ser un IntegerField opcional.

        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True),
        ),
        # Altera el campo 'poster_path' del modelo 'Movie' para ser un URLField opcional.

        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(blank=True),
        ),
        # Altera el campo 'release_date' del modelo 'Movie' para ser un DateTimeField opcional.

        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(blank=True),
        ),
        # Altera el campo 'revenue' del modelo 'Movie' para ser un IntegerField opcional.

        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(blank=True),
        ),
        # Altera el campo 'running_time' del modelo 'Movie' para ser un IntegerField opcional.

        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        # Altera el campo 'tmdb_id' del modelo 'Movie' para ser un IntegerField opcional, único y que puede ser nulo.
    ]
    # Define las operaciones de la migración.

